<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE context [
<!ELEMENT context (device | context-attribute)*>
<!ELEMENT context-attribute EMPTY>
<!ELEMENT device (channel | attribute | debug-attribute | buffer-attribute)*>
<!ELEMENT channel (scan-element? , attribute*)>
<!ELEMENT attribute EMPTY>
<!ELEMENT scan-element EMPTY>
<!ELEMENT debug-attribute EMPTY>
<!ELEMENT buffer-attribute EMPTY>
<!ATTLIST context name CDATA #REQUIRED>
<!ATTLIST context description CDATA #IMPLIED>
<!ATTLIST context-attribute name CDATA #REQUIRED>
<!ATTLIST context-attribute value CDATA #REQUIRED>
<!ATTLIST device id CDATA #REQUIRED>
<!ATTLIST device name CDATA #IMPLIED>
<!ATTLIST channel id CDATA #REQUIRED>
<!ATTLIST channel type (input | output) #REQUIRED>
<!ATTLIST channel name CDATA #IMPLIED>
<!ATTLIST scan-element index CDATA #REQUIRED>
<!ATTLIST scan-element format CDATA #REQUIRED>
<!ATTLIST scan-element scale CDATA #IMPLIED>
<!ATTLIST attribute name CDATA #REQUIRED>
<!ATTLIST attribute filename CDATA #IMPLIED>
<!ATTLIST attribute value CDATA #IMPLIED>
<!ATTLIST debug-attribute name CDATA #REQUIRED>
<!ATTLIST debug-attribute value CDATA #IMPLIED>
<!ATTLIST buffer-attribute name CDATA #REQUIRED>
<!ATTLIST buffer-attribute value CDATA #IMPLIED>
]>
<context name="network" description="192.168.2.1 Linux (none) 4.19.0-gbd9f616 #102 SMP PREEMPT Thu Sep 17 09:44:38 CEST 2020 armv7l">
    <context-attribute name="hw_model" value="Analog Devices M2k Rev.C (Z7010)"/>
    <context-attribute name="hw_model_variant" value="0"/>
    <context-attribute name="hw_serial" value="ADALM2000 Demo"/>
    <context-attribute name="fw_version" value="v0.26"/>
    <context-attribute name="cal,offset_pos_dac" value="0.018"/>
    <context-attribute name="cal,gain_pos_dac" value="0.998048"/>
    <context-attribute name="cal,offset_pos_adc" value="0.000730159"/>
    <context-attribute name="cal,gain_pos_adc" value="0.995132"/>
    <context-attribute name="cal,offset_neg_dac" value="0.0017"/>
    <context-attribute name="cal,gain_neg_dac" value="0.996722"/>
    <context-attribute name="cal,offset_neg_adc" value="-0.00167558"/>
    <context-attribute name="cal,gain_neg_adc" value="1.00724"/>
    <context-attribute name="local,kernel" value="4.19.0-gbd9f616"/>
    <context-attribute name="uri" value="ip:127.0.0.1"/>
    <context-attribute name="ip,ip-addr" value="127.0.0.1"/>
    <device id="iio:device0" name="m2k-adc">
        <channel id="voltage0" type="input">
            <scan-element index="0" format="le:s12/16&gt;&gt;0"/>
            <attribute name="calibbias" filename="in_voltage0_calibbias" value="1050"/>
            <attribute name="calibscale" filename="in_voltage0_calibscale" value="1.000000"/>
        </channel>
        <channel id="voltage1" type="input">
            <scan-element index="1" format="le:s12/16&gt;&gt;0"/>
            <attribute name="calibbias" filename="in_voltage1_calibbias" value="1060"/>
            <attribute name="calibscale" filename="in_voltage1_calibscale" value="1.000000"/>
        </channel>
        <attribute name="oversampling_ratio" value="0"/>
        <attribute name="sampling_frequency" value="100000000"/>
        <attribute name="sampling_frequency_available" value="1000 10000 100000 1000000 10000000 100000000"/>
        <buffer-attribute name="data_available" value="0"/>
        <buffer-attribute name="length_align_bytes" value="8"/>
        <buffer-attribute name="watermark" value="2048"/>
        <debug-attribute name="direct_reg_access" value="0xA0162"/>
    </device>
    <device id="iio:device1" name="xadc">
        <channel id="voltage5" name="vccoddr" type="input">
            <attribute name="raw" filename="in_voltage5_vccoddr_raw" value="1815"/>
            <attribute name="scale" filename="in_voltage5_vccoddr_scale" value="0.732421875"/>
        </channel>
        <channel id="voltage0" name="vccint" type="input">
            <attribute name="raw" filename="in_voltage0_vccint_raw" value="1352"/>
            <attribute name="scale" filename="in_voltage0_vccint_scale" value="0.732421875"/>
        </channel>
        <channel id="voltage4" name="vccpaux" type="input">
            <attribute name="raw" filename="in_voltage4_vccpaux_raw" value="2421"/>
            <attribute name="scale" filename="in_voltage4_vccpaux_scale" value="0.732421875"/>
        </channel>
        <channel id="temp0" type="input">
            <attribute name="offset" filename="in_temp0_offset" value="-2219"/>
            <attribute name="raw" filename="in_temp0_raw" value="2659"/>
            <attribute name="scale" filename="in_temp0_scale" value="123.040771484"/>
        </channel>
        <channel id="voltage7" name="vrefn" type="input">
            <attribute name="raw" filename="in_voltage7_vrefn_raw" value="-7"/>
            <attribute name="scale" filename="in_voltage7_vrefn_scale" value="0.732421875"/>
        </channel>
        <channel id="voltage1" name="vccaux" type="input">
            <attribute name="raw" filename="in_voltage1_vccaux_raw" value="2426"/>
            <attribute name="scale" filename="in_voltage1_vccaux_scale" value="0.732421875"/>
        </channel>
        <channel id="voltage2" name="vccbram" type="input">
            <attribute name="raw" filename="in_voltage2_vccbram_raw" value="1354"/>
            <attribute name="scale" filename="in_voltage2_vccbram_scale" value="0.732421875"/>
        </channel>
        <channel id="voltage3" name="vccpint" type="input">
            <attribute name="raw" filename="in_voltage3_vccpint_raw" value="1351"/>
            <attribute name="scale" filename="in_voltage3_vccpint_scale" value="0.732421875"/>
        </channel>
        <channel id="voltage8" type="input">
            <attribute name="raw" filename="in_voltage8_raw" value="2845"/>
            <attribute name="scale" filename="in_voltage8_scale" value="0.244140625"/>
        </channel>
        <channel id="voltage6" name="vrefp" type="input">
            <attribute name="raw" filename="in_voltage6_vrefp_raw" value="1696"/>
            <attribute name="scale" filename="in_voltage6_vrefp_scale" value="0.732421875"/>
        </channel>
        <attribute name="sampling_frequency" value="240384"/>
    </device>
    <device id="iio:device10" name="m2k-logic-analyzer-rx">
        <channel id="voltage0" type="input">
            <scan-element index="0" format="le:u1/16&gt;&gt;0"/>
            <attribute name="trigger" filename="in_voltage0_trigger" value="none"/>
            <attribute name="trigger_available" filename="in_voltage_trigger_available" value="none edge-any edge-rising edge-falling level-low level-high"/>
            <attribute name="trigger_delay" filename="in_voltage_trigger_delay" value="0"/>
            <attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" value="or"/>
            <attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" value="or and"/>
            <attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" value="trigger-logic"/>
            <attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" value="trigger-in disabled"/>
        </channel>
        <channel id="voltage1" type="input">
            <scan-element index="0" format="le:u1/16&gt;&gt;1"/>
            <attribute name="trigger" filename="in_voltage1_trigger" value="none"/>
            <attribute name="trigger_available" filename="in_voltage_trigger_available" value="none edge-any edge-rising edge-falling level-low level-high"/>
            <attribute name="trigger_delay" filename="in_voltage_trigger_delay" value="0"/>
            <attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" value="or"/>
            <attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" value="or and"/>
            <attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" value="trigger-logic"/>
            <attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" value="trigger-in disabled"/>
        </channel>
        <channel id="voltage2" type="input">
            <scan-element index="0" format="le:u1/16&gt;&gt;2"/>
            <attribute name="trigger" filename="in_voltage2_trigger" value="none"/>
            <attribute name="trigger_available" filename="in_voltage_trigger_available" value="none edge-any edge-rising edge-falling level-low level-high"/>
            <attribute name="trigger_delay" filename="in_voltage_trigger_delay" value="0"/>
            <attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" value="or"/>
            <attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" value="or and"/>
            <attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" value="trigger-logic"/>
            <attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" value="trigger-in disabled"/>
        </channel>
        <channel id="voltage3" type="input">
            <scan-element index="0" format="le:u1/16&gt;&gt;3"/>
            <attribute name="trigger" filename="in_voltage3_trigger" value="none"/>
            <attribute name="trigger_available" filename="in_voltage_trigger_available" value="none edge-any edge-rising edge-falling level-low level-high"/>
            <attribute name="trigger_delay" filename="in_voltage_trigger_delay" value="0"/>
            <attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" value="or"/>
            <attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" value="or and"/>
            <attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" value="trigger-logic"/>
            <attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" value="trigger-in disabled"/>
        </channel>
        <channel id="voltage4" type="input">
            <scan-element index="0" format="le:u1/16&gt;&gt;4"/>
            <attribute name="trigger" filename="in_voltage4_trigger" value="none"/>
            <attribute name="trigger_available" filename="in_voltage_trigger_available" value="none edge-any edge-rising edge-falling level-low level-high"/>
            <attribute name="trigger_delay" filename="in_voltage_trigger_delay" value="0"/>
            <attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" value="or"/>
            <attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" value="or and"/>
            <attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" value="trigger-logic"/>
            <attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" value="trigger-in disabled"/>
        </channel>
        <channel id="voltage5" type="input">
            <scan-element index="0" format="le:u1/16&gt;&gt;5"/>
            <attribute name="trigger" filename="in_voltage5_trigger" value="none"/>
            <attribute name="trigger_available" filename="in_voltage_trigger_available" value="none edge-any edge-rising edge-falling level-low level-high"/>
            <attribute name="trigger_delay" filename="in_voltage_trigger_delay" value="0"/>
            <attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" value="or"/>
            <attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" value="or and"/>
            <attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" value="trigger-logic"/>
            <attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" value="trigger-in disabled"/>
        </channel>
        <channel id="voltage6" type="input">
            <scan-element index="0" format="le:u1/16&gt;&gt;6"/>
            <attribute name="trigger" filename="in_voltage6_trigger" value="none"/>
            <attribute name="trigger_available" filename="in_voltage_trigger_available" value="none edge-any edge-rising edge-falling level-low level-high"/>
            <attribute name="trigger_delay" filename="in_voltage_trigger_delay" value="0"/>
            <attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" value="or"/>
            <attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" value="or and"/>
            <attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" value="trigger-logic"/>
            <attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" value="trigger-in disabled"/>
        </channel>
        <channel id="voltage7" type="input">
            <scan-element index="0" format="le:u1/16&gt;&gt;7"/>
            <attribute name="trigger" filename="in_voltage7_trigger" value="none"/>
            <attribute name="trigger_available" filename="in_voltage_trigger_available" value="none edge-any edge-rising edge-falling level-low level-high"/>
            <attribute name="trigger_delay" filename="in_voltage_trigger_delay" value="0"/>
            <attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" value="or"/>
            <attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" value="or and"/>
            <attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" value="trigger-logic"/>
            <attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" value="trigger-in disabled"/>
        </channel>
        <channel id="voltage8" type="input">
            <scan-element index="0" format="le:u1/16&gt;&gt;8"/>
            <attribute name="trigger" filename="in_voltage8_trigger" value="none"/>
            <attribute name="trigger_available" filename="in_voltage_trigger_available" value="none edge-any edge-rising edge-falling level-low level-high"/>
            <attribute name="trigger_delay" filename="in_voltage_trigger_delay" value="0"/>
            <attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" value="or"/>
            <attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" value="or and"/>
            <attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" value="trigger-logic"/>
            <attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" value="trigger-in disabled"/>
        </channel>
        <channel id="voltage9" type="input">
            <scan-element index="0" format="le:u1/16&gt;&gt;9"/>
            <attribute name="trigger" filename="in_voltage9_trigger" value="none"/>
            <attribute name="trigger_available" filename="in_voltage_trigger_available" value="none edge-any edge-rising edge-falling level-low level-high"/>
            <attribute name="trigger_delay" filename="in_voltage_trigger_delay" value="0"/>
            <attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" value="or"/>
            <attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" value="or and"/>
            <attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" value="trigger-logic"/>
            <attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" value="trigger-in disabled"/>
        </channel>
        <channel id="voltage10" type="input">
            <scan-element index="0" format="le:u1/16&gt;&gt;10"/>
            <attribute name="trigger" filename="in_voltage10_trigger" value="none"/>
            <attribute name="trigger_available" filename="in_voltage_trigger_available" value="none edge-any edge-rising edge-falling level-low level-high"/>
            <attribute name="trigger_delay" filename="in_voltage_trigger_delay" value="0"/>
            <attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" value="or"/>
            <attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" value="or and"/>
            <attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" value="trigger-logic"/>
            <attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" value="trigger-in disabled"/>
        </channel>
        <channel id="voltage11" type="input">
            <scan-element index="0" format="le:u1/16&gt;&gt;11"/>
            <attribute name="trigger" filename="in_voltage11_trigger" value="none"/>
            <attribute name="trigger_available" filename="in_voltage_trigger_available" value="none edge-any edge-rising edge-falling level-low level-high"/>
            <attribute name="trigger_delay" filename="in_voltage_trigger_delay" value="0"/>
            <attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" value="or"/>
            <attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" value="or and"/>
            <attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" value="trigger-logic"/>
            <attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" value="trigger-in disabled"/>
        </channel>
        <channel id="voltage12" type="input">
            <scan-element index="0" format="le:u1/16&gt;&gt;12"/>
            <attribute name="trigger" filename="in_voltage12_trigger" value="none"/>
            <attribute name="trigger_available" filename="in_voltage_trigger_available" value="none edge-any edge-rising edge-falling level-low level-high"/>
            <attribute name="trigger_delay" filename="in_voltage_trigger_delay" value="0"/>
            <attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" value="or"/>
            <attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" value="or and"/>
            <attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" value="trigger-logic"/>
            <attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" value="trigger-in disabled"/>
        </channel>
        <channel id="voltage13" type="input">
            <scan-element index="0" format="le:u1/16&gt;&gt;13"/>
            <attribute name="trigger" filename="in_voltage13_trigger" value="none"/>
            <attribute name="trigger_available" filename="in_voltage_trigger_available" value="none edge-any edge-rising edge-falling level-low level-high"/>
            <attribute name="trigger_delay" filename="in_voltage_trigger_delay" value="0"/>
            <attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" value="or"/>
            <attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" value="or and"/>
            <attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" value="trigger-logic"/>
            <attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" value="trigger-in disabled"/>
        </channel>
        <channel id="voltage14" type="input">
            <scan-element index="0" format="le:u1/16&gt;&gt;14"/>
            <attribute name="trigger" filename="in_voltage14_trigger" value="none"/>
            <attribute name="trigger_available" filename="in_voltage_trigger_available" value="none edge-any edge-rising edge-falling level-low level-high"/>
            <attribute name="trigger_delay" filename="in_voltage_trigger_delay" value="0"/>
            <attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" value="or"/>
            <attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" value="or and"/>
            <attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" value="trigger-logic"/>
            <attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" value="trigger-in disabled"/>
        </channel>
        <channel id="voltage15" type="input">
            <scan-element index="0" format="le:u1/16&gt;&gt;15"/>
            <attribute name="trigger" filename="in_voltage15_trigger" value="none"/>
            <attribute name="trigger_available" filename="in_voltage_trigger_available" value="none edge-any edge-rising edge-falling level-low level-high"/>
            <attribute name="trigger_delay" filename="in_voltage_trigger_delay" value="0"/>
            <attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" value="or"/>
            <attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" value="or and"/>
            <attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" value="trigger-logic"/>
            <attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" value="trigger-in disabled"/>
        </channel>
        <channel id="voltage16" type="input">
            <attribute name="trigger" filename="in_voltage16_trigger" value="none"/>
            <attribute name="trigger_available" filename="in_voltage_trigger_available" value="none edge-any edge-rising edge-falling level-low level-high"/>
            <attribute name="trigger_delay" filename="in_voltage_trigger_delay" value="0"/>
            <attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" value="or"/>
            <attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" value="or and"/>
            <attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" value="trigger-logic"/>
            <attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" value="trigger-in disabled"/>
        </channel>
        <channel id="voltage17" type="input">
            <attribute name="trigger" filename="in_voltage17_trigger" value="none"/>
            <attribute name="trigger_available" filename="in_voltage_trigger_available" value="none edge-any edge-rising edge-falling level-low level-high"/>
            <attribute name="trigger_delay" filename="in_voltage_trigger_delay" value="0"/>
            <attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" value="or"/>
            <attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" value="or and"/>
            <attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" value="trigger-logic"/>
            <attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" value="trigger-in disabled"/>
        </channel>
        <attribute name="data_delay_auto" value="auto"/>
        <attribute name="data_delay_auto_available" value="auto manual"/>
        <attribute name="data_in_delay" value="0"/>
        <attribute name="rate_mux" value="logic_analyzer"/>
        <attribute name="rate_mux_available" value="logic_analyzer oscilloscope"/>
        <attribute name="sampling_frequency" value="100000000"/>
        <attribute name="streaming" value="0"/>
        <attribute name="triggered" value="1"/>
        <buffer-attribute name="data_available" value="0"/>
        <buffer-attribute name="length_align_bytes" value="8"/>
        <buffer-attribute name="watermark" value="2048"/>
    </device>
    <device id="iio:device11" name="m2k-fabric">
        <channel id="voltage0" type="input">
            <attribute name="gain" filename="in_voltage0_gain" value="low"/>
            <attribute name="gain_available" filename="in_voltage_gain_available" value="low high"/>
            <attribute name="powerdown" filename="in_voltage_powerdown" value="1"/>
        </channel>
        <channel id="voltage0" type="output">
            <attribute name="powerdown" filename="out_voltage0_powerdown" value="1"/>
        </channel>
        <channel id="voltage3" type="output">
            <attribute name="user_supply_powerdown" filename="out_voltage3_user_supply_powerdown" value="1"/>
        </channel>
        <channel id="voltage4" type="output">
            <attribute name="done_led_overwrite_powerdown" filename="out_voltage4_done_led_overwrite_powerdown" value="0"/>
        </channel>
        <channel id="voltage1" type="output">
            <attribute name="powerdown" filename="out_voltage1_powerdown" value="1"/>
        </channel>
        <channel id="voltage2" type="output">
            <attribute name="user_supply_powerdown" filename="out_voltage2_user_supply_powerdown" value="1"/>
        </channel>
        <channel id="voltage1" type="input">
            <attribute name="gain" filename="in_voltage1_gain" value="low"/>
            <attribute name="gain_available" filename="in_voltage_gain_available" value="low high"/>
            <attribute name="powerdown" filename="in_voltage_powerdown" value="1"/>
        </channel>
        <attribute name="calibration_mode" value="none"/>
        <attribute name="calibration_mode_available" value="none adc_ref1 adc_ref2 adc_gnd dac"/>
        <attribute name="clk_powerdown" value="1"/>
    </device>
    <device id="iio:device12" name="m2k-adc-trigger">
        <channel id="voltage4" name="trigger_logic" type="input">
            <attribute name="mode" filename="in_voltage4_trigger_logic_mode" value="always"/>
            <attribute name="mode_available" filename="in_voltage4_trigger_logic_mode_available" value="gital_AND_analog !digital_XOR_analog"/>
            <attribute name="out_direction" filename="in_voltage4_trigger_logic_out_direction" value="in"/>
            <attribute name="out_direction_available" filename="in_voltage4_trigger_logic_out_direction_available" value="out in"/>
            <attribute name="out_select" filename="in_voltage4_trigger_logic_out_select" value="sw-trigger"/>
            <attribute name="out_select_available" filename="in_voltage4_trigger_logic_out_select_available" value="sw-trigger trigger-i-same-chan trigger-i-swap-chan trigger-adc trigger-in"/>
        </channel>
        <channel id="voltage5" name="trigger_logic" type="input">
            <attribute name="mode" filename="in_voltage5_trigger_logic_mode" value="always"/>
            <attribute name="mode_available" filename="in_voltage5_trigger_logic_mode_available" value="gital_AND_analog !digital_XOR_analog"/>
            <attribute name="out_direction" filename="in_voltage5_trigger_logic_out_direction" value="out"/>
            <attribute name="out_direction_available" filename="in_voltage5_trigger_logic_out_direction_available" value="out in"/>
            <attribute name="out_select" filename="in_voltage5_trigger_logic_out_select" value="sw-trigger"/>
            <attribute name="out_select_available" filename="in_voltage5_trigger_logic_out_select_available" value="sw-trigger trigger-i-same-chan trigger-i-swap-chan trigger-adc trigger-in"/>
        </channel>
        <channel id="voltage1" type="input">
            <attribute name="trigger" filename="in_voltage1_trigger" value="edge-rising"/>
            <attribute name="trigger_available" filename="in_voltage1_trigger_available" value="level-low level-high edge-rising edge-falling"/>
            <attribute name="trigger_hysteresis" filename="in_voltage1_trigger_hysteresis" value="0"/>
            <attribute name="trigger_level" filename="in_voltage1_trigger_level" value="0"/>
        </channel>
        <channel id="voltage6" name="trigger" type="input">
            <attribute name="delay" filename="in_voltage6_trigger_delay" value="0"/>
            <attribute name="embedded" filename="in_voltage6_trigger_embedded" value="0"/>
            <attribute name="logic_mode" filename="in_voltage6_trigger_logic_mode" value="a"/>
            <attribute name="logic_mode_available" filename="in_voltage6_trigger_logic_mode_available" value="  b a_OR_b a_AND_b a_XOR_b trigger_in a_OR_trigger_in b_OR_trigger_in a_OR_b_OR_trigger_in disabled"/>
        </channel>
        <channel id="voltage2" type="input">
            <attribute name="trigger" filename="in_voltage2_trigger" value="level-low"/>
            <attribute name="trigger_available" filename="in_voltage2_trigger_available" value="level-low level-high edge-any edge-rising edge-falling"/>
        </channel>
        <channel id="voltage0" type="input">
            <attribute name="trigger" filename="in_voltage0_trigger" value="edge-rising"/>
            <attribute name="trigger_available" filename="in_voltage0_trigger_available" value="level-low level-high edge-rising edge-falling"/>
            <attribute name="trigger_hysteresis" filename="in_voltage0_trigger_hysteresis" value="0"/>
            <attribute name="trigger_level" filename="in_voltage0_trigger_level" value="0"/>
        </channel>
        <channel id="voltage3" type="input">
            <attribute name="trigger" filename="in_voltage3_trigger" value="level-low"/>
            <attribute name="trigger_available" filename="in_voltage3_trigger_available" value="level-low level-high edge-any edge-rising edge-falling"/>
        </channel>
        <attribute name="holdoff_raw" value="0"/>
        <attribute name="sampling_frequency" value="100000000"/>
        <attribute name="streaming" value="0"/>
        <attribute name="triggered" value="1"/>
        <debug-attribute name="direct_reg_access" value="0x30000"/>
    </device>
    <device id="iio:device13" name="ad9963">
        <channel id="voltage1" type="output">
            <attribute name="raw" filename="out_voltage1_raw" value="0"/>
        </channel>
        <channel id="temp0" type="input">